import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service',
}

export default function TermsPage() {
  return (
    <div style={{ background: 'var(--background)', minHeight: '100vh' }}>
      <nav
        className="px-6 sm:px-10 py-5 flex items-center justify-between sticky top-0 z-10"
        style={{ borderBottom: '0.5px solid var(--border)', background: 'var(--background)' }}
      >
        <Link href="/" style={{ fontFamily: 'var(--font-fraunces)', fontSize: '15px' }}>
          <span style={{ color: 'var(--accent)' }}>Out</span>
          <span style={{ color: 'var(--text-primary)' }}>TheChat</span>
        </Link>
        <Link href="/" className="text-sm" style={{ color: 'var(--text-secondary)' }}>← Back</Link>
      </nav>

      <main className="max-w-2xl mx-auto px-6 py-16">
        <div className="mb-10">
          <div className="flex items-center gap-3 mb-5">
            <div style={{ width: '24px', height: '0.5px', background: 'var(--accent)' }} />
            <span style={{ fontSize: '11px', fontWeight: '500', letterSpacing: '0.14em', textTransform: 'uppercase', color: 'var(--accent)' }}>
              Legal
            </span>
          </div>
          <h1 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '36px', letterSpacing: '-0.02em', color: 'var(--text-primary)', marginBottom: '8px' }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)' }}>Last updated: April 2026</p>
        </div>

        <div style={{ fontSize: '14px', lineHeight: '1.8', color: 'var(--text-secondary)' }} className="space-y-8">
          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>1. Acceptance of Terms</h2>
            <p>By accessing or using OutTheChat (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>2. Use of the Service</h2>
            <p>OutTheChat provides AI-powered group trip planning tools. You may use the Service only for lawful purposes and in accordance with these Terms. You are responsible for all activity that occurs under your account.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>3. Accounts</h2>
            <p>You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. Notify us immediately of any unauthorized use at support@outthechat.com.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>4. AI-Generated Content</h2>
            <p>Trip itineraries, cost estimates, and recommendations are generated by AI and are provided for informational purposes only. We make no guarantees about the accuracy, completeness, or suitability of AI-generated content. Always verify travel information independently before making bookings or financial commitments.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>5. Payments</h2>
            <p>Group fund features are processed through Stripe. By using payment features, you agree to Stripe&apos;s Terms of Service. OutTheChat does not store full payment card details. All charges are displayed before confirmation.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>6. Intellectual Property</h2>
            <p>The Service and its original content (excluding user-generated content) are and will remain the exclusive property of OutTheChat. You may not copy, modify, or distribute any part of the Service without prior written consent.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>7. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, OutTheChat shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to travel losses, booking errors, or reliance on AI-generated recommendations.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>8. Termination</h2>
            <p>We may suspend or terminate your account at any time for violations of these Terms. You may delete your account at any time by contacting support@outthechat.com.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>9. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms. We will notify users of material changes by email.</p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'var(--font-fraunces)', fontSize: '18px', color: 'var(--text-primary)', marginBottom: '12px' }}>10. Contact</h2>
            <p>Questions about these Terms? Email us at <a href="mailto:support@outthechat.com" style={{ color: 'var(--accent)' }}>support@outthechat.com</a>.</p>
          </section>
        </div>
      </main>

      <footer className="px-6 sm:px-10 py-8 flex items-center justify-between" style={{ borderTop: '0.5px solid var(--border)' }}>
        <p className="text-xs" style={{ color: 'var(--text-muted)' }}>© 2026 OutTheChat</p>
        <Link href="/privacy" className="text-xs" style={{ color: 'var(--text-secondary)' }}>Privacy Policy</Link>
      </footer>
    </div>
  )
}
